#!/usr/bin/env python3
"""
Nitro Enclave Attestation Verifier

This script verifies proof packages generated by the Nitro Enclave demo.
It performs the following checks:
1. Parses the attestation document (COSE Sign1 structure)
2. Verifies the signature chain against AWS Nitro Root CA
3. Checks PCR0 matches the expected value from docker_image_info
4. Recomputes SHA-256(input || output) and compares to user_data

Usage:
    python verify.py <proof_package.json> <input.json> [--expected-pcr0 <hex>]

Download AWS Nitro Root CA:
    wget https://aws-nitro-enclaves.amazonaws.com/AWS_NitroEnclaves_Root-G1.zip
    unzip AWS_NitroEnclaves_Root-G1.zip
    # The certificate is in: AWS_NitroEnclaves_Root-G1.pem
"""

import argparse
import base64
import hashlib
import json
import sys
from pathlib import Path
from typing import Optional, Tuple

try:
    import cbor2
    from cryptography import x509
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec, utils
    from cryptography.hazmat.backends import default_backend
    from cryptography.exceptions import InvalidSignature
    from pycose.messages import Sign1Message
    from pycose.keys import EC2Key
    from pycose.keys.curves import P384
    from pycose.algorithms import Es384
except ImportError as e:
    print(f"Missing dependency: {e}")
    print("Install with: pip install -r requirements.txt")
    sys.exit(1)


# Path to AWS Nitro Root CA certificate
ROOT_CA_PATH = Path(__file__).parent / "AWS_NitroEnclaves_Root-G1.pem"


class VerificationError(Exception):
    """Raised when verification fails"""
    pass


def load_root_ca() -> x509.Certificate:
    """Load the AWS Nitro Root CA certificate"""
    if not ROOT_CA_PATH.exists():
        raise VerificationError(
            f"Root CA certificate not found at {ROOT_CA_PATH}\n"
            "Download from: https://aws-nitro-enclaves.amazonaws.com/AWS_NitroEnclaves_Root-G1.zip"
        )

    with open(ROOT_CA_PATH, "rb") as f:
        return x509.load_pem_x509_certificate(f.read(), default_backend())


def parse_attestation_document(attestation_b64: str) -> Tuple[dict, bytes, bytes, list]:
    """
    Parse a COSE Sign1 attestation document.

    Returns:
        Tuple of (payload_dict, signature, leaf_cert_der, cabundle)
        For mock attestations: (payload_dict, b"", b"", [])
    """
    attestation_bytes = base64.b64decode(attestation_b64)

    # Check for mock attestation
    if attestation_bytes.startswith(b"MOCK"):
        print("[!] WARNING: This is a MOCK attestation document (not from real NSM)")
        mock_payload = json.loads(attestation_bytes[4:])
        return mock_payload, b"", b"", []

    # Parse COSE Sign1 structure
    # The attestation document is a COSE_Sign1 structure:
    # [protected_header, unprotected_header, payload, signature]
    try:
        cose_obj = cbor2.loads(attestation_bytes)
    except Exception as e:
        raise VerificationError(f"Failed to parse CBOR: {e}")

    # COSE Sign1 is tagged with 18
    if isinstance(cose_obj, cbor2.CBORTag):
        if cose_obj.tag != 18:
            raise VerificationError(f"Unexpected CBOR tag: {cose_obj.tag}, expected 18 (COSE_Sign1)")
        cose_obj = cose_obj.value

    if not isinstance(cose_obj, list) or len(cose_obj) != 4:
        raise VerificationError(f"Invalid COSE Sign1 structure")

    protected, unprotected, payload, signature = cose_obj

    # Parse payload (CBOR encoded)
    payload_dict = cbor2.loads(payload)

    # Extract leaf certificate and CA bundle separately
    leaf_cert_der = payload_dict.get("certificate", b"")
    cabundle = payload_dict.get("cabundle", [])

    return payload_dict, signature, leaf_cert_der, cabundle


def verify_certificate_chain(leaf_cert_der: bytes, cabundle: list, root_ca: x509.Certificate) -> x509.Certificate:
    """
    Verify the certificate chain from leaf to root.

    Nitro Attestation cabundle order: [root, intermediate1, intermediate2, ..., leaf_issuer]
    The leaf certificate is separate (in the 'certificate' field).

    Returns the leaf certificate if verification succeeds.
    """
    # Parse leaf certificate
    try:
        leaf_cert = x509.load_der_x509_certificate(leaf_cert_der, default_backend())
    except Exception as e:
        raise VerificationError(f"Failed to parse leaf certificate: {e}")

    # Parse cabundle certificates
    ca_certs = []
    for cert_der in cabundle:
        try:
            if isinstance(cert_der, str):
                cert_der = cert_der.encode()
            cert = x509.load_der_x509_certificate(cert_der, default_backend())
            ca_certs.append(cert)
        except Exception as e:
            raise VerificationError(f"Failed to parse CA certificate: {e}")

    if not ca_certs:
        raise VerificationError("Empty CA bundle")

    # Build chain: leaf → cabundle[-1] → ... → cabundle[0] → root_ca
    # cabundle[0] is the root/self-signed, cabundle[-1] is the leaf's direct issuer
    chain = [leaf_cert] + list(reversed(ca_certs))

    # Verify each link: child signed by parent
    for i in range(len(chain) - 1):
        child = chain[i]
        parent = chain[i + 1]
        try:
            parent.public_key().verify(
                child.signature,
                child.tbs_certificate_bytes,
                ec.ECDSA(child.signature_hash_algorithm)
            )
        except (InvalidSignature, Exception) as e:
            raise VerificationError(
                f"Certificate chain verification failed at level {i}: "
                f"child={child.subject}, parent={parent.subject}, error={e}"
            )

    # Verify cabundle[0] (root of the bundle) is signed by the AWS Root CA
    bundle_root = ca_certs[0]
    try:
        root_ca.public_key().verify(
            bundle_root.signature,
            bundle_root.tbs_certificate_bytes,
            ec.ECDSA(bundle_root.signature_hash_algorithm)
        )
    except (InvalidSignature, Exception) as e:
        raise VerificationError(f"AWS Root CA signature verification failed: {e}")

    return leaf_cert


def verify_signature(attestation_b64: str, leaf_cert: x509.Certificate) -> bool:
    """Verify the COSE Sign1 signature using the leaf certificate's public key.

    COSE_Sign1 = [protected, unprotected, payload, signature]
    Sig_structure = ["Signature1", protected, external_aad, payload]
    The signature is ECDSA over SHA-384 of the CBOR-encoded Sig_structure.
    """
    attestation_bytes = base64.b64decode(attestation_b64)

    try:
        cose_obj = cbor2.loads(attestation_bytes)
        if isinstance(cose_obj, cbor2.CBORTag):
            cose_obj = cose_obj.value

        protected, unprotected, payload, signature = cose_obj

        # Build the Sig_structure for COSE_Sign1
        # Sig_structure = ["Signature1", protected, external_aad, payload]
        sig_structure = cbor2.dumps(["Signature1", protected, b"", payload])

        # Extract EC public key from certificate
        pub_key = leaf_cert.public_key()
        if not isinstance(pub_key, ec.EllipticCurvePublicKey):
            raise VerificationError("Certificate does not contain an EC public key")

        # COSE signatures use raw r||s format (not DER)
        # Convert to DER for cryptography library
        r = int.from_bytes(signature[:len(signature)//2], 'big')
        s = int.from_bytes(signature[len(signature)//2:], 'big')
        der_signature = utils.encode_dss_signature(r, s)

        # Verify ECDSA signature over the Sig_structure
        pub_key.verify(
            der_signature,
            sig_structure,
            ec.ECDSA(hashes.SHA384())
        )

        return True

    except InvalidSignature:
        return False
    except Exception as e:
        raise VerificationError(f"Signature verification failed: {e}")


def verify_pcrs(payload: dict, expected_pcr0: Optional[str] = None) -> bool:
    """Verify PCR values match expected"""
    pcrs = payload.get("pcrs", {})

    if not pcrs:
        print("[!] No PCR values in attestation")
        return False

    # Display PCR values
    print("\n[*] PCR Values:")
    for idx, value in sorted(pcrs.items()):
        if isinstance(value, bytes):
            hex_value = value.hex()
        else:
            hex_value = value
        print(f"    PCR{idx}: {hex_value}")

    if expected_pcr0:
        actual_pcr0 = pcrs.get(0, pcrs.get("0", b""))
        if isinstance(actual_pcr0, bytes):
            actual_pcr0 = actual_pcr0.hex()

        if actual_pcr0.lower() != expected_pcr0.lower():
            print(f"\n[!] PCR0 MISMATCH!")
            print(f"    Expected: {expected_pcr0}")
            print(f"    Actual:   {actual_pcr0}")
            return False
        print(f"\n[+] PCR0 matches expected value")

    return True


def verify_user_data(payload: dict, input_bytes: bytes, output_bytes: bytes) -> bool:
    """Verify user_data matches SHA-256(input || output)"""
    # Compute expected user_data
    hasher = hashlib.sha256()
    hasher.update(input_bytes)
    hasher.update(output_bytes)
    expected_user_data = hasher.digest()

    # Get actual user_data from attestation
    actual_user_data = payload.get("user_data")

    if actual_user_data is None:
        print("[!] No user_data in attestation document")
        return False

    # Handle different formats
    if isinstance(actual_user_data, str):
        # Hex encoded
        actual_user_data = bytes.fromhex(actual_user_data)
    elif isinstance(actual_user_data, bytes):
        pass
    else:
        print(f"[!] Unexpected user_data type: {type(actual_user_data)}")
        return False

    print(f"\n[*] User Data Verification:")
    print(f"    Expected: {expected_user_data.hex()}")
    print(f"    Actual:   {actual_user_data.hex()}")

    if actual_user_data != expected_user_data:
        print("\n[!] USER DATA MISMATCH - output may have been tampered with!")
        return False

    print("\n[+] User data matches - input/output integrity verified")
    return True


def main():
    parser = argparse.ArgumentParser(
        description="Verify Nitro Enclave attestation proof package"
    )
    parser.add_argument(
        "proof_package",
        help="Path to proof_package.json"
    )
    parser.add_argument(
        "input_file",
        help="Path to input.json"
    )
    parser.add_argument(
        "--expected-pcr0",
        help="Expected PCR0 value (hex)",
        default=None
    )
    parser.add_argument(
        "--skip-signature",
        action="store_true",
        help="Skip signature verification (for mock attestations)"
    )

    args = parser.parse_args()

    print("=" * 60)
    print("Nitro Enclave Attestation Verifier")
    print("=" * 60)

    # Load files
    try:
        with open(args.proof_package, "r") as f:
            proof_package = json.load(f)
        with open(args.input_file, "rb") as f:
            input_bytes = f.read()
    except Exception as e:
        print(f"[!] Failed to load files: {e}")
        sys.exit(1)

    print(f"\n[*] Loaded proof package: {args.proof_package}")
    print(f"[*] Loaded input: {args.input_file}")

    # Extract components
    attestation_b64 = proof_package.get("attestation_document", "")
    output = proof_package.get("output", {})
    output_raw_b64 = proof_package.get("output_raw", "")
    docker_info = proof_package.get("docker_image_info", {})

    # Use output_raw (exact bytes from enclave) for hash verification
    # This avoids re-serialization mismatches between Rust serde_json and Python json
    if output_raw_b64:
        output_bytes = base64.b64decode(output_raw_b64)
        print(f"[*] Using output_raw for hash verification ({len(output_bytes)} bytes)")
    else:
        # Fallback: re-serialize (may not match if key ordering differs)
        output_bytes = json.dumps(output, separators=(',', ':')).encode()
        print("[!] WARNING: output_raw not found, using re-serialized output (hash may not match)")

    # Check if it's a mock attestation
    attestation_bytes = base64.b64decode(attestation_b64)
    is_mock = attestation_bytes.startswith(b"MOCK")

    if is_mock:
        print("\n" + "=" * 60)
        print("WARNING: MOCK ATTESTATION DETECTED")
        print("This proof was not generated inside a real Nitro Enclave.")
        print("Signature verification will be skipped.")
        print("=" * 60)

    # Parse attestation document
    print("\n[*] Parsing attestation document...")
    try:
        payload, signature, leaf_cert_der, cabundle = parse_attestation_document(attestation_b64)
    except VerificationError as e:
        print(f"[!] FAIL: {e}")
        sys.exit(1)

    print(f"[+] Attestation document parsed successfully")
    print(f"    Module ID: {payload.get('module_id', 'N/A')}")
    print(f"    Digest: {payload.get('digest', 'N/A')}")

    all_checks_passed = True

    # Verify certificate chain and signature (skip for mock)
    if not is_mock and not args.skip_signature:
        print("\n[*] Verifying certificate chain...")
        try:
            root_ca = load_root_ca()
            leaf_cert = verify_certificate_chain(leaf_cert_der, cabundle, root_ca)
            print("[+] Certificate chain verified")

            print("\n[*] Verifying COSE signature...")
            if verify_signature(attestation_b64, leaf_cert):
                print("[+] Signature verified")
            else:
                print("[!] FAIL: Signature verification failed")
                all_checks_passed = False
        except VerificationError as e:
            print(f"[!] FAIL: {e}")
            all_checks_passed = False
    elif is_mock:
        print("\n[*] Skipping signature verification (mock attestation)")
    else:
        print("\n[*] Skipping signature verification (--skip-signature)")

    # Verify PCRs
    expected_pcr0 = args.expected_pcr0 or docker_info.get("pcr0")
    if expected_pcr0 and not expected_pcr0.startswith("<"):
        if not verify_pcrs(payload, expected_pcr0):
            all_checks_passed = False
    else:
        print("\n[*] PCR verification skipped (no expected value provided)")
        verify_pcrs(payload)  # Just display PCR values

    # Verify user_data (input/output integrity)
    print("\n[*] Verifying input/output integrity...")
    if not verify_user_data(payload, input_bytes, output_bytes):
        all_checks_passed = False

    # Final result
    print("\n" + "=" * 60)
    if all_checks_passed:
        if is_mock:
            print("RESULT: PASS (with warnings - mock attestation)")
        else:
            print("RESULT: PASS")
        print("=" * 60)
        print("\nThe proof package is valid:")
        if not is_mock:
            print("  - Attestation signature verified against AWS Nitro Root CA")
        print("  - Input/output integrity verified via user_data hash")
        if expected_pcr0 and not expected_pcr0.startswith("<"):
            print("  - PCR0 matches expected enclave measurement")
        sys.exit(0)
    else:
        print("RESULT: FAIL")
        print("=" * 60)
        print("\nVerification failed. The proof package may be invalid or tampered with.")
        sys.exit(1)


if __name__ == "__main__":
    main()
